#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ_ROOT_DIR="$(dirname "$SCRIPT_DIR")"

print_usage() {
  echo "Linker: Creates symbolic links to submodules."
  echo "Usage: $0 link|unlink|help"
}

link() {
  ln -s ../../include/ $PROJ_ROOT_DIR/moc32json/external/commons
  ln -s ../../include/ $PROJ_ROOT_DIR/lite2d/external/commons
  ln -s ../../include/ $PROJ_ROOT_DIR/lite2d-vtuber/external/commons
}

unlink() {
  rm $PROJ_ROOT_DIR/moc32json/external/commons
  rm $PROJ_ROOT_DIR/lite2d/external/commons
  rm $PROJ_ROOT_DIR/lite2d-vtuber/external/commons
}

if [[ -z $1 || $1 == "help" ]]; then
  print_usage
  exit 1
elif [[ $1 == "link" ]]; then
  echo "Creating symbolic links to submodules..."
  unlink
  link
elif [[ $1 == "unlink" ]]; then
  echo "Removing symbolic links to submodules..."
  unlink
else
  print_usage
  exit 1
fi
